# this build works with container based envs
sudo: false

language: scala

# need to keep this in step with build.sbt
scala:
  - 2.10.4
  - 2.11.6

jdk:
  - oraclejdk7
  - openjdk7
  
notifications:
  email:
    - chris@nappin.com